# Generated by Django 5.2.3 on 2025-09-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('home_address', models.TextField()),
                ('designation', models.CharField(choices=[('Business Manager', 'Business Manager'), ('Human Resource Manager', 'Human Resource Manager'), ('Lecturer', 'Lecturer'), ('Software Engineer', 'Software Engineer'), ('Programmer', 'Programmer'), ('Business Analyst', 'Business Analyst')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('home_address', models.TextField()),
                ('password', models.CharField(max_length=128)),
                ('course', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
